[package]
name = "audio-rs"
version = "0.2.1"
edition = "2021"

[lib]
crate-type = ["cdylib", "rlib"]

[dependencies]
wasm-bindgen = "0.2"
console_error_panic_hook = "0.1.7"
rayon = "1.5"
symphonia = { version = "0.5", features = ["all", "opt-simd"] }

[profile.release]
lto = true
opt-level = 's'
